/**
 * Design Tokens
 * Single source of truth for the entire design system.
 *
 * Import pattern:
 *   import { colors, CUBIC_BEZIER, spacing } from '@gi-lab/design-tokens'
 *
 * SCSS variables are generated by:
 *   make sync-tokens  →  scripts/sync-tokens.ts →  tokens.generated.scss
 */

export { colors } from './colors';
export type { ColorScale, ColorKey } from './colors';

export { CUBIC_BEZIER, DURATION, toCSSCubicBezier, toArray } from './easing';
export type { EasingKey, DurationKey } from './easing';

export { spacing, borderRadius, typography } from './spacing';
export type { SpacingKey, TypographyTokens } from './spacing';
