#!/usr/bin/env node
/**
 * Token Sync Script
 * Reads packages/design-tokens and generates:
 *   1. apps/web/src/styles/tokens.generated.scss  — CSS custom props + SCSS vars
 * Usage: make sync-tokens
 */

import { writeFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

const COLORS: Record<string, string> = {
  'bg-void': '#050507',
  'bg-surface': '#0d0d14',
  'bg-elevated': '#16161f',
  'primary-50': '#e0fffe',
  'primary-100': '#b3fffe',
  'primary-200': '#7dfffd',
  'primary-300': '#40fffa',
  'primary-400': '#00f5f0',
  'primary-500': '#00d4cf',
  'primary-600': '#00a8a4',
  'primary-700': '#007b78',
  'primary-800': '#004f4d',
  'primary-900': '#002424',
  'accent-50': '#f3e8ff',
  'accent-100': '#e4c8ff',
  'accent-200': '#cea5ff',
  'accent-300': '#b57bff',
  'accent-400': '#9e55ff',
  'accent-500': '#8832ff',
  'accent-600': '#6e1fdd',
  'accent-700': '#5511aa',
  'accent-800': '#3d0877',
  'accent-900': '#240444',
  'neutral-50': '#f2f2f7',
  'neutral-100': '#e0e0ee',
  'neutral-200': '#c0c0d8',
  'neutral-300': '#9090b8',
  'neutral-400': '#606090',
  'neutral-500': '#404068',
  'neutral-600': '#282840',
  'neutral-700': '#1a1a2c',
  'neutral-800': '#10101e',
  'neutral-900': '#08080f',
  'semantic-success': '#00ff88',
  'semantic-warning': '#ffcc00',
  'semantic-error': '#ff3366',
  'semantic-info': '#0099ff',
};

const EASING: Record<string, [number, number, number, number]> = {
  'out-expo': [0.16, 1, 0.3, 1],
  'in-expo': [0.7, 0, 0.84, 0],
  'in-out-expo': [0.87, 0, 0.13, 1],
  'out-quint': [0.22, 1, 0.36, 1],
  'in-quint': [0.64, 0, 0.78, 0],
  'in-out-quint': [0.83, 0, 0.17, 1],
  'out-back': [0.34, 1.56, 0.64, 1],
  'in-out-back': [0.68, -0.6, 0.32, 1.6],
  'out-cubic': [0.33, 1, 0.68, 1],
  'in-out-cubic': [0.65, 0, 0.35, 1],
  linear: [0, 0, 1, 1],
};

const DURATION: Record<string, number> = {
  instant: 0,
  fast: 150,
  normal: 300,
  slow: 600,
  glacial: 1200,
};

async function main(): Promise<void> {
  const lines: string[] = [
    `/**`,
    ` * Generated SCSS Tokens`,
    ` * ⚠️  AUTO-GENERATED by: make sync-tokens`,
    ` * Source: packages/design-tokens/src/`,
    ` * Do NOT edit manually.`,
    ` */`,
    '',
    `// SCSS Variables`,
    ...Object.entries(COLORS).map(([k, v]) => `$${k}: ${v};`),
    '',
    ...Object.entries(EASING).map(([k, v]) => `$ease-${k}: cubic-bezier(${v.join(', ')});`),
    '',
    ...Object.entries(DURATION).map(([k, v]) => `$duration-${k}: ${v}ms;`),
    '',
    `// Semantic Aliases`,
    `// Shorthand for the default (500) scale of each color ramp.`,
    `$primary: $primary-500;`,
    `$accent: $accent-500;`,
    `$neutral: $neutral-500;`,
    '',
    `// CSS Custom Properties Mixin`,
    `// Use @include tokens.define-css-vars() in globals.scss (not in CSS modules).`,
    `@mixin define-css-vars {`,
    `  :root {`,
    `    // Colors`,
    ...Object.entries(COLORS).map(([k, v]) => `    --color-${k}: ${v};`),
    ``,
    `    // Easing`,
    ...Object.entries(EASING).map(([k, v]) => `    --ease-${k}: cubic-bezier(${v.join(', ')});`),
    ``,
    `    // Durations`,
    ...Object.entries(DURATION).map(([k, v]) => `    --duration-${k}: ${v}ms;`),
    `  }`,
    `}`,
  ];

  const scssContent = lines.join('\n') + '\n';
  const scssOutput = resolve(ROOT, 'apps/web/src/styles/tokens.generated.scss');
  await writeFile(scssOutput, scssContent);
  console.log(`✅  Generated: apps/web/src/styles/tokens.generated.scss`);
  console.log(
    `   ${Object.keys(COLORS).length} colors, ${Object.keys(EASING).length} easing, ${Object.keys(DURATION).length} durations`,
  );
}

main().catch((err: unknown) => {
  console.error('❌  sync-tokens failed:', err);
  process.exit(1);
});
